version: "3.9"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-container
    ports:
      - "8300:8300"
    restart: always
    environment:
      - TZ=America/Bogota
      - REDIS_HOST=localhost
      - REDIS_PORT=6300
      - DEPLOYMENT=prod
      - PYTHONPATH=/app
      - DBHOST=localhost
      - DBUSER=mluser
      - DBPASSWORD=victorpassword
      - DB=db
    network_mode: "host"

