// Generated by https://quicktype.io

export interface PostConsultsReponse {
  data:    Consult[];
  code:    number;
  message: string;
}

export interface HomeGetConsultsResponse {
  data: Table[];
  code: number;
  message: string;
}

export interface Table {
  code: string;
  data: Consult[];
  created_at: string;
}

export interface Consult {
  category: string;
  url: string;
}
